with open('donnee\\sauvegarde.txt', 'w') as file:
    file.write("LvL:\n")
    file.write("1\n")
    file.write("ID de Zone:")
    file.write("\n")
    file.write("-1;0;0")
    file.write("\n")
    file.write("Money:")
    file.write("\n0")
    file.write("\nNiveau de Quetes:")
    file.write("\n0")
    file.write("\nsac:")
    file.write("\nNULL;NULL;NULL;LOCK;LOCK;LOCK;LOCK;LOCK;LOCK")
    file.write("\nTouches:")
    file.write("\n0b11010;0b100;0b10110;0b111;0b101100;0b1000")